build:
  apt_packages:
    - 'libcairo2-dev'
    - 'libgirepository-2.0-dev'
  jobs:
    post_install:
      - 'pip install poetry'
      - 'VIRTUAL_ENV="$READTHEDOCS_VIRTUALENV_PATH" poetry install --all-extras --with=docs'
  os: 'ubuntu-24.04'
  tools:
    python: '3.12'
sphinx:
  configuration: 'docs/conf.py'
  fail_on_warning: false
version: 2
